"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productosRoutes = void 0;
const express_1 = require("express");
const productos_controller_1 = require("../controllers/productos_controller");
exports.productosRoutes = (0, express_1.Router)();
exports.productosRoutes.get('/getproductos', productos_controller_1.getProducto);
exports.productosRoutes.get('/getproductosbyid/:id', productos_controller_1.getProductoById);
exports.productosRoutes.post('/createproductos', productos_controller_1.createProducto);
exports.productosRoutes.delete('/deleteproducto/:id', productos_controller_1.deleteProducto);
exports.productosRoutes.put('/updateproducto/:id', productos_controller_1.updateProducto);
