"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tablasRoutes = void 0;
const express_1 = require("express");
const tabla_controller_1 = require("../controllers/tabla_controller");
exports.tablasRoutes = (0, express_1.Router)();
exports.tablasRoutes.get('/gettabla', tabla_controller_1.getTabla);
exports.tablasRoutes.get('/gettablabyid/:id', tabla_controller_1.getTablaById);
exports.tablasRoutes.post('/createtabla', tabla_controller_1.createTabla);
exports.tablasRoutes.delete('/deletetabla/:id', tabla_controller_1.deleteTabla);
exports.tablasRoutes.put('/updatetabla/:id', tabla_controller_1.updateTabla);
